#!/usr/bin/env python3

from lib import Application
import argparse

parser = argparse.ArgumentParser(description='Browse Gophersites')
parser.add_argument('address', help='the website to visit')
args = parser.parse_args()

app = Application()
app.run(args)
